# Generated by Django 3.0.2 on 2020-02-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('excelfile', models.FileField(null=True, upload_to='file/', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('username', models.IntegerField(null=True)),
                ('social_platform', models.CharField(max_length=20, null=True)),
                ('media', models.IntegerField(null=True)),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
                ('engagement', models.IntegerField(null=True)),
                ('authenticity', models.IntegerField(null=True)),
                ('highlight_reel_count', models.IntegerField(null=True)),
                ('is_business_account', models.IntegerField(null=True)),
                ('is_private', models.IntegerField(null=True)),
                ('is_verified', models.IntegerField(null=True)),
                ('is_barter', models.IntegerField(null=True)),
                ('business_category', models.CharField(max_length=30, null=True)),
                ('join_date', models.DateTimeField(null=True)),
                ('last_updated_on', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('price_per_pic_post', models.IntegerField(null=True)),
                ('cost_per_engagement', models.DecimalField(decimal_places=4, max_digits=15)),
                ('ex_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.ExcelModel')),
            ],
        ),
    ]
